FROM python:3.11.4-slim 
 
RUN apt-get update && \ 
  apt-get install -y gcc libpq-dev && \ 
  apt clean && \ 
  rm -rf /var/cache/apt/* 
 
ENV PYTHONDONTWRITEBYTECODE=1 \ 
  PYTHONUNBUFFERED=1 \ 
  PYTHONIOENCODING=utf-8 


COPY /requirements.txt /tmp/requirements.txt 
 
RUN pip install -U pip && \ 
  pip install -r /tmp/requirements.txt 
 

COPY . /src 
ENV PATH "$PATH:/src/scripts" 
 
WORKDIR /src 

CMD [ "uvicorn", "app.main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]